server:
  port: 8761

eureka:
  instance:
    hostname: discovery
  server:
    response-cache-update-interval-ms: 500
    eviction-interval-timer-in-ms: 500
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
